"""Add Number column to TestTable

Revision ID: 1b4a17f9ff87
Revises: 814489d8edab
Create Date: 2025-10-15 23:27:26.362510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b4a17f9ff87'
down_revision: Union[str, Sequence[str], None] = '814489d8edab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TestTable', sa.Column('Number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TestTable', 'Number')
    # ### end Alembic commands ###
