"""Add merchantID to healthdata table

Revision ID: 1b51e10b1607
Revises: ae5ac11c2d58
Create Date: 2025-10-16 14:20:33.913524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b51e10b1607'
down_revision: Union[str, Sequence[str], None] = 'ae5ac11c2d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
