"""Change health Data to reflect prediction models more acurately

Revision ID: 1f7a5d4938ff
Revises: 1b51e10b1607
Create Date: 2025-11-09 10:05:46.676680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f7a5d4938ff'
down_revision: Union[str, Sequence[str], None] = '1b51e10b1607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('HealthData', sa.Column('HeightCentimetreMeters',
                  sa.Numeric(precision=5, scale=2), nullable=True))
    op.alter_column('HealthData', 'SmokingStatus',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Integer(),
                    existing_nullable=True)
    op.alter_column('HealthData', 'MaritalStatus',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Integer(),
                    existing_nullable=True)
    op.alter_column('HealthData', 'WorkingStatus',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Integer(),
                    existing_nullable=True)
    op.drop_column('HealthData', 'HeightMeters')
    op.drop_column('HealthData', 'Exercise')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('HealthData', sa.Column('Exercise', mysql.TINYINT(
        display_width=1), autoincrement=False, nullable=True))
    op.add_column('HealthData', sa.Column('HeightMeters',
                  mysql.DECIMAL(precision=3, scale=2), nullable=True))
    op.alter_column('HealthData', 'WorkingStatus',
                    existing_type=sa.Integer(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.alter_column('HealthData', 'MaritalStatus',
                    existing_type=sa.Integer(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.alter_column('HealthData', 'SmokingStatus',
                    existing_type=sa.Integer(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.drop_column('HealthData', 'HeightCentimetreMeters')
    # ### end Alembic commands ###
