"""Remove exercise row

Revision ID: 7b3bb2401dfd
Revises: 1f7a5d4938ff
Create Date: 2025-11-09 10:09:27.634731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3bb2401dfd'
down_revision: Union[str, Sequence[str], None] = '1f7a5d4938ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
