"""Fix HeightCentimetres naming

Revision ID: 9fc0998ce231
Revises: 7b3bb2401dfd
Create Date: 2025-11-09 11:38:20.748706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9fc0998ce231'
down_revision: Union[str, Sequence[str], None] = '7b3bb2401dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('HealthData', sa.Column('HeightCentimetres', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_column('HealthData', 'HeightCentimetreMeters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('HealthData', sa.Column('HeightCentimetreMeters', mysql.DECIMAL(precision=5, scale=2), nullable=True))
    op.drop_column('HealthData', 'HeightCentimetres')
    # ### end Alembic commands ###
