"""Initial Schema

Revision ID: c7da9b40c87d
Revises: 
Create Date: 2025-10-14 22:57:06.129750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7da9b40c87d'
down_revision: Union[str, Sequence[str], None] = '81a354f03cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AccountRole',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('RoleName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('RoleID')
    )
    op.create_table('Permission',
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.Column('PermissionName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('PermissionID')
    )
    op.create_table('UserAccount',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('FullName', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('IsValidated', sa.Boolean(), nullable=True),
    sa.Column('TokenVersion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('HealthData',
    sa.Column('HealthDataID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('WeightKilograms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('HeightMeters', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('Gender', sa.Boolean(), nullable=True),
    sa.Column('BloodGlucose', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('APHigh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('APLow', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('HighCholesterol', sa.Boolean(), nullable=True),
    sa.Column('Exercise', sa.Boolean(), nullable=True),
    sa.Column('HyperTension', sa.Boolean(), nullable=True),
    sa.Column('HeartDisease', sa.Boolean(), nullable=True),
    sa.Column('Diabetes', sa.Boolean(), nullable=True),
    sa.Column('Alcohol', sa.Boolean(), nullable=True),
    sa.Column('SmokingStatus', sa.Boolean(), nullable=True),
    sa.Column('MaritalStatus', sa.Boolean(), nullable=True),
    sa.Column('WorkingStatus', sa.Boolean(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['UserAccount.UserID'], ),
    sa.PrimaryKeyConstraint('HealthDataID')
    )
    op.create_table('RolePermission',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.Column('AssignedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['PermissionID'], ['Permission.PermissionID'], ),
    sa.ForeignKeyConstraint(['RoleID'], ['AccountRole.RoleID'], ),
    sa.PrimaryKeyConstraint('RoleID', 'PermissionID')
    )
    op.create_table('UserAccountRole',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('AssignedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['RoleID'], ['AccountRole.RoleID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['UserAccount.UserID'], ),
    sa.PrimaryKeyConstraint('RoleID', 'UserID')
    )
    op.create_table('UserAccountValidationToken',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('ValidationToken', sa.String(length=999), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['UserAccount.UserID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_table('Prediction',
    sa.Column('PredictionID', sa.Integer(), nullable=False),
    sa.Column('HealthDataID', sa.Integer(), nullable=True),
    sa.Column('StrokeChance', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('DiabetesChance', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('CVDChance', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['HealthDataID'], ['HealthData.HealthDataID'], ),
    sa.PrimaryKeyConstraint('PredictionID')
    )
    op.create_table('Recommendation',
    sa.Column('RecommendationID', sa.Integer(), nullable=False),
    sa.Column('HealthDataID', sa.Integer(), nullable=True),
    sa.Column('ExerciseRecommendation', sa.Text(), nullable=True),
    sa.Column('DietRecommendation', sa.Text(), nullable=True),
    sa.Column('LifestyleRecommendation', sa.Text(), nullable=True),
    sa.Column('DietToAvoidRecommendation', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['HealthDataID'], ['HealthData.HealthDataID'], ),
    sa.PrimaryKeyConstraint('RecommendationID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recommendation')
    op.drop_table('Prediction')
    op.drop_table('UserAccountValidationToken')
    op.drop_table('UserAccountRole')
    op.drop_table('RolePermission')
    op.drop_table('HealthData')
    op.drop_table('UserAccount')
    op.drop_table('Permission')
    op.drop_table('AccountRole')
    # ### end Alembic commands ###
